print("Now counting things")
print("This language doesn't feel especially structured if I'm honest")
print("But I've only ever written maybe 3 classes")
print(10 + 20 + 30)
print(10 * 2)
print(30 - 15)
print(6 % 3)
print("Lovely")
